parserOptions:
    ecmaVersion: 9
    sourceType: module

env:
    browser: true

extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'

settings:
    version: detect

rules:
    no-console: 1
    react/prop-types: 0
    semi: 2